[default]

# NOME DO MODELO
APPNAME = 'OCR'

# DIRETÓRIO DE SAVE DOS LOGS
DIR_SAVE_LOGS = 'LOGS'

# ARQUIVO DE SAVE DOS LOGS - LOGGING
LOG_FILENAME = 'LOG_OCR.log'

# LEVEL DE CRITICIDADE DO LOG A SER REGISTRADO
LOGLEVEL = 'DEBUG'
LOGLEVEL_FILE = 'DEBUG'
LOGLEVEL_CONSOLE = 'DEBUG'

FORMAT_TYPES_ACCEPTED = ["jpg", "png"]

# INICIANDO A VARIÁVEL DE LOGGERS
LOGGERS = {}

# PARÂMETROS DO OCR - TESSERACT
TESSERACT_LANG = 'eng'
TESSERACT_PSM = '1'
TESSERACT_OEM = '3'

# PARÂMETRO PARA APLICAÇÃO DO PRÉ PROCESSAMENTO DA IMAGEM (CROPPED E WARPED)
PRE_PROC_IMAGE = true
VIEW_PRE_PROC_IMAGE = false

# PARÂMETRO DO TIPO DE RETORNO DO OCR
TYPE_OCR = "TEXTO"
VIEW_OCR_COMPLETE = false

# TIPO DE FORMATO DO OUTPUT QUANDO UTILIZADO OCR COMPLETO
OUTPUT_TYPE_IMAGE_DATA = 'DATAFRAME'

[development]